# Generated by Django 3.0.4 on 2020-03-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(max_length=20)),
                ('image_link', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
