# Generated by Django 3.0.4 on 2020-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [ 
		('shop', '0003_auto_20200331_0718'),
	]

	operations = [
		migrations.CreateModel(
			name='CampaignItems',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('item', models.ManyToManyField(to='shop.Product')),
			],
		),
	]
